# Generated by Django 5.2.3 on 2025-09-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_variant_alter_cartitem_product'),
    ]

    operations = [
    ]
