# Generated by Django 5.2.3 on 2025-11-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
