# Generated by Django 5.2.3 on 2025-11-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_request',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('RETURNED', 'Returned')], default='PLACED', max_length=20),
        ),
    ]
