# Generated by Django 5.2.3 on 2025-11-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_cancel_reason_orderitem_canceled_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='returned_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
