# Generated by Django 5.2.3 on 2025-11-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_cancel_reason_and_more'),
    ]

    operations = [
    ]
