# Generated by Django 5.1.4 on 2025-09-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_order_address'),
    ]

    operations = [
        
    ]
