# Generated by Django 5.2.3 on 2025-11-05 04:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/<your-cloud-name>/image/upload/v123456789/default_profile.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
