# Generated by Django 5.2.3 on 2025-10-04 04:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_productvariant_sale_price'),
        ('wishlist', '0002_wishlistitem_added_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='variant',
            field=models.ForeignKey(default=datetime.datetime(2025, 10, 4, 4, 20, 19, 612416, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='store.productvariant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'product', 'variant')},
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
