# Generated by Django 5.2.3 on 2025-10-04 04:25

import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_productvariant_sale_price'),
        ('wishlist', '0003_alter_wishlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariant'),
        ),
    ]
