# Generated by Django 5.2.3 on 2025-10-04 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_productvariant_sale_price'),
        ('wishlist', '0004_alter_wishlistitem_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariant'),
        ),
    ]
