# Generated by Django 5.2.3 on 2025-10-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_alter_wishlistitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='variant',
        ),
    ]
