# Generated by Django 5.2.3 on 2025-07-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_options_rename_quatity_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('out_of_stock', 'Out of Stock')], default='draft', max_length=20),
        ),
    ]
