# Generated by Django 5.2.3 on 2025-07-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_created_at_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('out of stock', 'Out of Stock')], default='draft', max_length=20),
        ),
    ]
