# Generated by Django 5.2.3 on 2025-07-11 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=datetime.datetime(2025, 7, 11, 7, 44, 23, 559496, tzinfo=datetime.timezone.utc), upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
