# Generated by Django 5.2.3 on 2025-07-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_coupon_remove_address_line1_remove_address_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default_profile.png', upload_to='profile/'),
        ),
    ]
