# Generated by Django 5.1.4 on 2025-09-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='return_request',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='None', max_length=10),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
