# Generated by Django 5.1.4 on 2025-09-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_review_order_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
