# Generated by Django 5.1.4 on 2025-09-23 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_category_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AddField(
            model_name='address',
            name='address_id',
            field=models.IntegerField(default=datetime.datetime(2025, 9, 23, 12, 53, 42, 834279, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
