# Generated by Django 5.1.4 on 2025-09-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_address_id_address_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
