# Generated by Django 5.1.4 on 2025-09-24 04:34

from django.db import migrations

def create_variants(apps, schema_editor):
    Product = apps.get_model("store", "Product")
    ProductVariant = apps.get_model("store", "ProductVariant")
    for p in Product.objects.all():
        # Create only if no variants exist
        if not ProductVariant.objects.filter(product=p).exists():
            ProductVariant.objects.create(
                product=p,
                size="M",  # default size for existing items
                price=p.price,
                quantity=p.quantity,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_productvariant'),
    ]

    operations = [
        migrations.RunPython(create_variants),
    ]
