# Generated by Django 5.2.3 on 2025-09-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_create_default_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AddField(
            model_name='address',
            name='address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
