# Generated by Django 5.2.3 on 2025-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_productvariant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
