# Generated by Django 5.2.3 on 2025-09-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_address_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
