# Generated by Django 5.2.3 on 2025-11-11 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime(2025, 11, 11, 7, 1, 26, 317472, tzinfo=datetime.timezone.utc), max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
