# Generated by Django 5.2.3 on 2025-11-11 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_rename_active_coupon_is_active_coupon_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='expiry_date',
            new_name='valid_to',
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
