# Generated by Django 5.2.3 on 2025-11-11 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_rename_active_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_value',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime(2025, 11, 11, 7, 2, 30, 85531, tzinfo=datetime.timezone.utc), max_digits=10),
            preserve_default=False,
        ),
    ]
