# Generated by Django 5.2.3 on 2025-11-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_discount_amount'),
    ]

    operations = [
    ]
